void initialize( int *argc, char ***argv );
void finalize();
void setState( int newState );
int getRandomNumberOfRooms( int P );
void incrementLamport( int lamportIn );
int max( int numberA, int numberB );
void sendMessageForAll( int messageType );
void sendMessageForSingleThread( int messageType, int receiverId );
bool isMyLamportLower( int inputLamport, int inputThreadId );
void incrementCounterACKP( int messageSender );
bool senderNotInAgreedForRoom( int messageSender );
bool gotEnoughACKP();
bool isEnoughFreeRooms();
void waitingForRoomPush( int messageSender, int messageValue );
void agreedForRoomPush( int messageSender, int messageValue );